import './globals.css'

export const metadata = {
  title: 'Aikos Portfolio',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-gradient bg-cover bg-[#ddf0f8]'>{children}</body>
    </html>
  )
}
